@startuml PlantUML Color Themes - Snazzy

' "Tomorrow night eighties" color theme (see https://github.com/chriskempson/tomorrow-theme)
!define Background   #282a36
!define CurrentLine  #2b2f3e
!define Selection    #52535d
!define Foregound    #f1f1f0
!define Comment      #676d91
!define Red          #ff5c57
!define Orange       #f7ad45
!define Yellow       #f3f99d
!define Green        #5af78e
!define Aqua         #9aedfe
!define Blue         #57c7ff
!define Purple       #ff6ac1

skinparam Shadowing false
skinparam backgroundColor #282a36
skinparam Arrow {
  Color Foregound
  FontColor Foregound
  FontStyle Bold
}
skinparam Default {
  FontName PragmataPro Liga Mono
  FontColor #f1f1f0
}
skinparam package {
  FontColor Purple
  BackgroundColor CurrentLine
  BorderColor Selection
}
skinparam node {
  FontColor Yellow
  BackgroundColor CurrentLine
  BorderColor Selection
}
skinparam component {
  BackgroundColor Selection
  BorderColor Blue
  FontColor Blue
  Style uml2
}
skinparam database {
  BackgroundColor CurrentLine
  BorderColor Selection
  FontColor Orange
}

skinparam cloud {
  BackgroundColor CurrentLine
  BorderColor Selection
}

skinparam interface {
  BackgroundColor CurrentLine
  BorderColor Selection
  FontColor Green
}

@enduml
