skinparam BackgroundColor 282a36
skinparam shadowing false
skinparam RoundCorner 1
skinparam ArrowColor f1f1f0
skinparam FontColor f1f1f0
skinparam SequenceLifeLineBorderColor f1f1f0
skinparam SequenceGroupHeaderFontColor f1f1f0
skinparam SequenceGroupFontColor f1f1f0
skinparam SequenceGroupBorderColor f1f1f0
skinparam SequenceGroupBorderThickness 1

skinparam sequenceDivider {
    BorderColor f1f1f0
    BorderThickness 1
    FontColor f1f1f0
}

skinparam participant {
    BackgroundColor ff5c57
    BorderColor ff5c57
    FontColor White
}

skinparam database {
    BackgroundColor 9aedfe
    BorderColor f1f1f0
    FontColor f1f1f0
}

skinparam entity {
    BackgroundColor f7ad45
    BorderColor f1f1f0
    FontColor f1f1f0
}

skinparam note {
    BackgroundColor 5af78e
    BorderColor 5af78e
    FontColor f1f1f0
}

skinparam actor {
    BackgroundColor f1f1f0
    BorderColor f1f1f0
    FontColor f1f1f0
}

skinparam boundary {
    BackgroundColor f3f99d
    BorderColor f1f1f0
    FontColor f1f1f0
}

skinparam control {
    BackgroundColor f3f99d
    BorderColor f1f1f0
    FontColor f1f1f0
}

skinparam collections {
    BackgroundColor ff5c57
    BorderColor f1f1f0
    FontColor f1f1f0
}
